<?php
/**
 * Created by PhpStorm.
 * User: matias
 * Date: 02/07/19
 * Time: 20:02
 */

namespace Patrones\Efectivos;


use Patrones\Interfaces\IEfectivoDeGot;

class Cientifica extends ManejadorEfectivos implements IEfectivoDeGot
{
    public function accidentes($presentes= [])
    {
        if(!array_key_exists("cientifica",$presentes)){
            $presentes["cientifica"] = 1;
        }else{
            $presentes["cientifica"] ++;
        }
        print_r("Policia Cientifica " . $this->nombre . " disponible para el accidente \n");
        return parent::accidentes($presentes);
    }

    public function amenazasDeBomba($orden = [])
    {
        $orden[] = "cientifica";
        print_r("Policia Cientifica " . $this->nombre . " disponible para la amenaza de bomba \n");
        return parent::amenazasDeBomba($orden); // TODO: Change the autogenerated stub
    }
}