<?php
/**
 * Created by PhpStorm.
 * User: matias
 * Date: 02/07/19
 * Time: 19:52
 */

namespace Patrones\Efectivos;


use Patrones\Interfaces\IEfectivoDeGot;

class Comisarios extends ManejadorEfectivos  implements IEfectivoDeGot
{
    public function robos()
    {
        print_r("Comisario " . $this->nombre . " disponible para el robo \n");

        return parent::robos();
    }

    public function amenazasDeBomba($orden = [])
    {
        $orden[] = "comisario";
        print_r("Comisario " . $this->nombre . " disponible para la amenaza de bomba \n");
        return parent::amenazasDeBomba($orden); // TODO: Change the autogenerated stub
    }

}